//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagiZile.Acadiverse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_es_mx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_es_mx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagiZile.Acadiverse.Properties.Resources_es_mx", typeof(Resources_es_mx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su cuenta ha sido prohibida permanentemente por violar reiterada o severamente nuestro Código de conducta. La razón específica dada fue: $ 1. Si crees que te prohibieron por error, puedes ir a http: //acadiverse.magizile.com/account/appeal para apelar esta prohibición..
        /// </summary>
        public static string str_account_permabanned {
            get {
                return ResourceManager.GetString("str_account_permabanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su cuenta ha sido prohibida hasta $ 1 por la siguiente razón: $ 2..
        /// </summary>
        public static string str_account_tempbanned {
            get {
                return ResourceManager.GetString("str_account_tempbanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede realizar esta acción ya que actualmente tiene prohibido enviar mensajes de chat / enviar usuarios PM que no son moderadores. Por favor contáctenos si cree que esto es un error..
        /// </summary>
        public static string str_banned_from_chat {
            get {
                return ResourceManager.GetString("str_banned_from_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede realizar esta acción ya que actualmente tiene prohibido publicar contenido en Acadiverse. Por favor contáctenos si cree que esto es un error..
        /// </summary>
        public static string str_banned_from_publishing {
            get {
                return ResourceManager.GetString("str_banned_from_publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, introduzca su contraseña..
        /// </summary>
        public static string str_blank_password {
            get {
                return ResourceManager.GetString("str_blank_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese su nombre de usuario..
        /// </summary>
        public static string str_blank_username {
            get {
                return ResourceManager.GetString("str_blank_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al conectar con el servidor. Por favor revise su conexion a internet. Nuestros servidores también pueden estar inactivos; Si este es el caso, espere unos minutos y / o vuelva a intentarlo más tarde..
        /// </summary>
        public static string str_connection_error {
            get {
                return ResourceManager.GetString("str_connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contenido, &quot;$ 1&quot;, fue eliminado de Acadiverse por la siguiente razón: $ 2..
        /// </summary>
        public static string str_content_removed_message_contents {
            get {
                return ResourceManager.GetString("str_content_removed_message_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contenido ha sido eliminado..
        /// </summary>
        public static string str_content_removed_message_subject {
            get {
                return ResourceManager.GetString("str_content_removed_message_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que deseas eliminar este mensaje? ¡Esto no se puede deshacer!.
        /// </summary>
        public static string str_delete_message_confirmation {
            get {
                return ResourceManager.GetString("str_delete_message_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu contraseña es incorrecta..
        /// </summary>
        public static string str_incorrect_passwrod {
            get {
                return ResourceManager.GetString("str_incorrect_passwrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe una cuenta con este nombre de usuario..
        /// </summary>
        public static string str_incorrect_username {
            get {
                return ResourceManager.GetString("str_incorrect_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás segura de que deseas cerrar sesión?.
        /// </summary>
        public static string str_logout_confirmation {
            get {
                return ResourceManager.GetString("str_logout_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Mensaje eliminado por una moderadora]..
        /// </summary>
        public static string str_message_deleted_by_moderator {
            get {
                return ResourceManager.GetString("str_message_deleted_by_moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Mensaje eliminado por la usuario]..
        /// </summary>
        public static string str_message_deleted_by_user {
            get {
                return ResourceManager.GetString("str_message_deleted_by_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede enviar PM a este usuario porque lo ha bloqueado..
        /// </summary>
        public static string str_pm_user_blocked {
            get {
                return ResourceManager.GetString("str_pm_user_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede enviar PM a este usuario porque ha elegido no recibir PM de usuarios que no son moderadores..
        /// </summary>
        public static string str_pm_user_opted_out {
            get {
                return ResourceManager.GetString("str_pm_user_opted_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cerrado la sesión porque hay un problema con sus credenciales..
        /// </summary>
        public static string str_problem_with_credentials {
            get {
                return ResourceManager.GetString("str_problem_with_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está a punto de reportar $ 1 por la siguiente razón: $ 2. Tenga en cuenta que los informes se toman muy en serio y que el envío de informes falsos puede resultar en una prohibición. ¿Continuar con la remodelación de este usuario?.
        /// </summary>
        public static string str_report_confirmation {
            get {
                return ResourceManager.GetString("str_report_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ 1 ha reportado $ 2 por la siguiente razón: $ 3. El contexto del informe (el contenido por el cual $ 1 informó $ 2) es: $ 4. Por favor revise este contenido de inmediato..
        /// </summary>
        public static string str_report_message_contents {
            get {
                return ResourceManager.GetString("str_report_message_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ 1 ha reportado $ 2..
        /// </summary>
        public static string str_report_message_subject {
            get {
                return ResourceManager.GetString("str_report_message_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta acción no se pudo realizar porque su mensaje contiene un insulto racial. Has ganado una huelga por esta acción. Si intenta enviar este tipo de mensajes $ 1 más veces, se le prohibió de chat / enviar MPs..
        /// </summary>
        public static string str_slur_entered {
            get {
                return ResourceManager.GetString("str_slur_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su envío no se pudo publicar porque el envío o sus metadatos (título, descripción y / o etiquetas) contienen un insulto racial. Has recibido una huelga por esta acción. Si intenta publicar dicho contenido $ 1 más veces, se le prohibirá publicar cualquier cosa en Acadiverse..
        /// </summary>
        public static string str_submission_slur_entered {
            get {
                return ResourceManager.GetString("str_submission_slur_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su envío no se pudo publicar porque el envío o sus metadatos (título, descripción y / o etiquetas) contienen una mala palabra. Has recibido una huelga por esta acción. Si intenta publicar dicho contenido $ 1 más veces, se le prohibirá publicar cualquier cosa en Acadiverse..
        /// </summary>
        public static string str_submission_swear_word_entered {
            get {
                return ResourceManager.GetString("str_submission_swear_word_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta acción no se pudo realizar porque su mensaje contiene lenguaje incorrecto o contenido sugerente. Has ganado una huelga por esta acción. Si intenta enviar dichos mensajes $ 1 más veces, se le prohibió de chat / enviar MPs..
        /// </summary>
        public static string str_swear_word_entered {
            get {
                return ResourceManager.GetString("str_swear_word_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se le ha prohibido automáticamente enviar chat / PM porque ha intentado enviar un mensaje de chat / PM con malas palabras o insultos raciales / culturales demasiadas veces..
        /// </summary>
        public static string str_too_many_chat_strikes {
            get {
                return ResourceManager.GetString("str_too_many_chat_strikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se le ha prohibido automáticamente publicar contenido en Acadiverse porque ha intentado publicar algo con una palabrota o insulto racial / cultural en él o sus metadatos (título, descripción y / o etiquetas) demasiadas veces..
        /// </summary>
        public static string str_too_many_publishing_strikes {
            get {
                return ResourceManager.GetString("str_too_many_publishing_strikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibió una advertencia por el siguiente motivo: $ 1..
        /// </summary>
        public static string str_warning_message_contents {
            get {
                return ResourceManager.GetString("str_warning_message_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has recibido una advertencia..
        /// </summary>
        public static string str_warning_message_subject {
            get {
                return ResourceManager.GetString("str_warning_message_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta característica solo está disponible para $ cuentas..
        /// </summary>
        public static string str_wrong_account_type {
            get {
                return ResourceManager.GetString("str_wrong_account_type", resourceCulture);
            }
        }
    }
}
