//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagiZile.UserInteractions.ParentalControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagiZile.UserInteractions.ParentalControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anus
        ///butt
        ///arse
        ///butt
        ///ass
        ///butt
        ///bastard
        ///illegitimate child
        ///bitch
        ///female dog
        ///blowjob
        ///intercourse
        ///boner
        ///erection
        ///chesticle
        ///breast
        ///cock
        ///boy thingy
        ///cunt
        ///girl thingy
        ///crap
        ///darn
        ///dick
        ///boy thingy
        ///damn
        ///darn
        ///hell
        ///heck
        ///goddamn
        ///gosh darn
        ///fap
        ///touch
        ///masturbate
        ///touch
        ///dildo
        ///pleasure toy
        ///condom
        ///male birth control
        ///tampon
        ///female birth control
        ///viagra
        ///male enhancement drugs
        ///nigger
        ///African-American
        ///nigga
        ///African-American
        ///jap
        ///Japanese person
        ///piss
        ///urinate
        ///shit
        ///feces
        ///shat
        ///defecated
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BadWordList {
            get {
                return ResourceManager.GetString("BadWordList", resourceCulture);
            }
        }
    }
}
