//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagiZile.Acadiverse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagiZile.Acadiverse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_profile_banned_user {
            get {
                object obj = ResourceManager.GetObject("img_profile_banned_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_profile_default {
            get {
                object obj = ResourceManager.GetObject("img_profile_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been permanently banned for repeatedly or severely violating our Code of Conduct. The specific reason given was: $1. If you believe that you were banned in error, you can go to http://acadiverse.magizile.xom/account/appeal to appeal this ban..
        /// </summary>
        public static string str_account_permabanned {
            get {
                return ResourceManager.GetString("str_account_permabanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been banned until $1 for the following reason: $2..
        /// </summary>
        public static string str_account_tempbanned {
            get {
                return ResourceManager.GetString("str_account_tempbanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be a member of Acadiverse for $1 years..
        /// </summary>
        public static string str_achievement_member_anniversary_description {
            get {
                return ResourceManager.GetString("str_achievement_member_anniversary_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 Anniversary.
        /// </summary>
        public static string str_achievement_member_anniversary_title {
            get {
                return ResourceManager.GetString("str_achievement_member_anniversary_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a perfect score on a quiz..
        /// </summary>
        public static string str_achievement_perfect_quiz_score_description {
            get {
                return ResourceManager.GetString("str_achievement_perfect_quiz_score_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aced It.
        /// </summary>
        public static string str_achievement_perfect_quiz_score_title {
            get {
                return ResourceManager.GetString("str_achievement_perfect_quiz_score_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a submission featured..
        /// </summary>
        public static string str_achievement_top_publisher_description {
            get {
                return ResourceManager.GetString("str_achievement_top_publisher_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Publisher.
        /// </summary>
        public static string str_achievement_top_publisher_title {
            get {
                return ResourceManager.GetString("str_achievement_top_publisher_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been automatically banned because you have received your $1 warning..
        /// </summary>
        public static string str_automatic_ban_reason {
            get {
                return ResourceManager.GetString("str_automatic_ban_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not perform this action as you are currently banned from sending chat messages/PMing users who are not moderators. Please contact us if you believe that this is a mistake..
        /// </summary>
        public static string str_banned_from_chat {
            get {
                return ResourceManager.GetString("str_banned_from_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not perform this action as you are currently banned from publshing content to Acadiverse. Please contact us if you believe that this is a mistake..
        /// </summary>
        public static string str_banned_from_publishing {
            get {
                return ResourceManager.GetString("str_banned_from_publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        public static string str_blank_password {
            get {
                return ResourceManager.GetString("str_blank_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username..
        /// </summary>
        public static string str_blank_username {
            get {
                return ResourceManager.GetString("str_blank_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to block this user? They will not be able to send you any PMs or comment on your submissions, and they will also be automatically blocked from any chats that you owm!.
        /// </summary>
        public static string str_block_user_confirmation {
            get {
                return ResourceManager.GetString("str_block_user_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to block this user from this chat? They will not be able to send any more chat messages!.
        /// </summary>
        public static string str_block_user_from_chat_confirmation {
            get {
                return ResourceManager.GetString("str_block_user_from_chat_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action could not be performed because you have been blocked from this chat. Please contact one of the chat moderators if you believe that this is in error..
        /// </summary>
        public static string str_blocked_from_chat {
            get {
                return ResourceManager.GetString("str_blocked_from_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action could not be perfoemed as the chat has been deleted. Chats can be deleted by the owner, or they can be deleted by an Acadiverse moderator or an admin for violating the Terms of Service or Code of Conduct..
        /// </summary>
        public static string str_chat_deleted {
            get {
                return ResourceManager.GetString("str_chat_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the server. Please check your Internet connection. Our servers may also be down; if this is the case, please wait a few minutes and/or try again later..
        /// </summary>
        public static string str_connection_error {
            get {
                return ResourceManager.GetString("str_connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your content, &quot;$1&quot;, was removed from Acadiverse for the following reason: $2..
        /// </summary>
        public static string str_content_removed_message_contents {
            get {
                return ResourceManager.GetString("str_content_removed_message_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your content has been removed..
        /// </summary>
        public static string str_content_removed_message_subject {
            get {
                return ResourceManager.GetString("str_content_removed_message_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this message? This can NOT be undone!.
        /// </summary>
        public static string str_delete_message_confirmation {
            get {
                return ResourceManager.GetString("str_delete_message_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is incorrect..
        /// </summary>
        public static string str_incorrect_password {
            get {
                return ResourceManager.GetString("str_incorrect_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account exists with this username..
        /// </summary>
        public static string str_incorrect_username {
            get {
                return ResourceManager.GetString("str_incorrect_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to log out?.
        /// </summary>
        public static string str_logout_confirmation {
            get {
                return ResourceManager.GetString("str_logout_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [message removed by a moderator]..
        /// </summary>
        public static string str_message_deleted_by_moderator {
            get {
                return ResourceManager.GetString("str_message_deleted_by_moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [message removed by user]..
        /// </summary>
        public static string str_message_deleted_by_user {
            get {
                return ResourceManager.GetString("str_message_deleted_by_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot afford this item. It costs $1 Acadicoins and you currently have $2..
        /// </summary>
        public static string str_not_enough_money {
            get {
                return ResourceManager.GetString("str_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least $1 Reputation Points to perform this action..
        /// </summary>
        public static string str_not_enough_reputation_points {
            get {
                return ResourceManager.GetString("str_not_enough_reputation_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats! You have recieved the &quot;$1&quot; achievement and gained $2 Reputation Points and $3 Acadicoins!.
        /// </summary>
        public static string str_notification_achievement_recieved {
            get {
                return ResourceManager.GetString("str_notification_achievement_recieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 new notifications..
        /// </summary>
        public static string str_notification_count {
            get {
                return ResourceManager.GetString("str_notification_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have gotten your first upvote on your submission &quot;$1&quot;!.
        /// </summary>
        public static string str_notification_first_submission_upvote {
            get {
                return ResourceManager.GetString("str_notification_first_submission_upvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 mentioned you in chat..
        /// </summary>
        public static string str_notification_mentioned_in_chat {
            get {
                return ResourceManager.GetString("str_notification_mentioned_in_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 mentioned you in the comments for the submission &quot;$2&quot;..
        /// </summary>
        public static string str_notification_mentioned_in_comments {
            get {
                return ResourceManager.GetString("str_notification_mentioned_in_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 has sent you a PM..
        /// </summary>
        public static string str_notification_pm {
            get {
                return ResourceManager.GetString("str_notification_pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 has commented on your submission &quot;$2&quot;..
        /// </summary>
        public static string str_notification_submission_comment {
            get {
                return ResourceManager.GetString("str_notification_submission_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats! Your submission, &quot;$1&quot;, has been featured on the Submissions page!.
        /// </summary>
        public static string str_notification_submission_featured {
            get {
                return ResourceManager.GetString("str_notification_submission_featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have gotten your $1 upvote on your submission &quot;$1&quot;!.
        /// </summary>
        public static string str_notification_upvote_milestone {
            get {
                return ResourceManager.GetString("str_notification_upvote_milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot PM this user because they have blocked you..
        /// </summary>
        public static string str_pm_user_blocked {
            get {
                return ResourceManager.GetString("str_pm_user_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot PM this user because they have chosen not to receive PMs from users who are not moderators..
        /// </summary>
        public static string str_pm_user_opted_out {
            get {
                return ResourceManager.GetString("str_pm_user_opted_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action could not be performed because the chat is private and you have not been given the appropriate permissions to access it..
        /// </summary>
        public static string str_private_chat_insufficient_permissions {
            get {
                return ResourceManager.GetString("str_private_chat_insufficient_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out as there is a problem with your credentials..
        /// </summary>
        public static string str_problem_with_credentials {
            get {
                return ResourceManager.GetString("str_problem_with_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to report $1 for the following reason: $2. Please note that reports are taken very seriously, and that sending false reports may result in a ban. Proceed with reporfting this user?.
        /// </summary>
        public static string str_report_confirmation {
            get {
                return ResourceManager.GetString("str_report_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 has reported $2 for the following reason: $3. The context of the report (the content that $1 reported $2) for is: $4. Please review this content immediately..
        /// </summary>
        public static string str_report_message_contents {
            get {
                return ResourceManager.GetString("str_report_message_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 has reported $2..
        /// </summary>
        public static string str_report_message_subject {
            get {
                return ResourceManager.GetString("str_report_message_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action could not be performed because your message contains a racial slur. You have earned a strike for this action. If you attempt to send such messages $1 more times, you will be banned from chatting/sending PMs..
        /// </summary>
        public static string str_slur_entered {
            get {
                return ResourceManager.GetString("str_slur_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your submission could not be published because the submission or its metadata (title, description, and/or tags) contains a racial/cultural slur. You have recieved a strike for this action. If you attempt to publish such content $1 more times, you will be banned from publishing anything to Acadiverse..
        /// </summary>
        public static string str_submission_slur_entered {
            get {
                return ResourceManager.GetString("str_submission_slur_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your submission could not be published because the submission or its metadata (title, description, and/or tags) contains a swear word. You have recieved a strike for this action. If you attempt to publish such content $1 more times, you will be banned from publishing anything to Acadiverse..
        /// </summary>
        public static string str_submission_swear_word_entered {
            get {
                return ResourceManager.GetString("str_submission_swear_word_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action could not be performed because your message contains bad language or suggestive content. You have earned a strike for this action. If you attempt to send such messages $1 more times, you will be banned from chatting/sending PMs..
        /// </summary>
        public static string str_swear_word_entered {
            get {
                return ResourceManager.GetString("str_swear_word_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been automatically banned from sending chat/PMs because you have attempted to send a chat message/PM with swear words or racial/cultural slurs in it too many times..
        /// </summary>
        public static string str_too_many_chat_strikes {
            get {
                return ResourceManager.GetString("str_too_many_chat_strikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been automatically banned from publishing content to Acadiverse because you have attempted to publish something with a swear word or racial/cultural slur in it or its metadata (title, description, and/or tags) too many times..
        /// </summary>
        public static string str_too_many_publishing_strikes {
            get {
                return ResourceManager.GetString("str_too_many_publishing_strikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have recieved a warning for the following reason: $1. .
        /// </summary>
        public static string str_warning_message_contents {
            get {
                return ResourceManager.GetString("str_warning_message_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have recieved a warning..
        /// </summary>
        public static string str_warning_message_subject {
            get {
                return ResourceManager.GetString("str_warning_message_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is only available to $ accounts..
        /// </summary>
        public static string str_wrong_account_type {
            get {
                return ResourceManager.GetString("str_wrong_account_type", resourceCulture);
            }
        }
    }
}
